# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_flatten_test')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_flatten_test')
    _flatten_test = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_flatten_test', [dirname(__file__)])
        except ImportError:
            import _flatten_test
            return _flatten_test
        try:
            _mod = imp.load_module('_flatten_test', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _flatten_test = swig_import_helper()
    del swig_import_helper
else:
    import _flatten_test
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _flatten_test.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _flatten_test.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _flatten_test.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _flatten_test.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _flatten_test.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _flatten_test.SwigPyIterator_equal(self, x)

    def copy(self):
        return _flatten_test.SwigPyIterator_copy(self)

    def next(self):
        return _flatten_test.SwigPyIterator_next(self)

    def __next__(self):
        return _flatten_test.SwigPyIterator___next__(self)

    def previous(self):
        return _flatten_test.SwigPyIterator_previous(self)

    def advance(self, n):
        return _flatten_test.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _flatten_test.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _flatten_test.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _flatten_test.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _flatten_test.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _flatten_test.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _flatten_test.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _flatten_test.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _flatten_test.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _flatten_test.StringVector___nonzero__(self)

    def __bool__(self):
        return _flatten_test.StringVector___bool__(self)

    def __len__(self):
        return _flatten_test.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _flatten_test.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _flatten_test.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _flatten_test.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _flatten_test.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _flatten_test.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _flatten_test.StringVector___setitem__(self, *args)

    def pop(self):
        return _flatten_test.StringVector_pop(self)

    def append(self, x):
        return _flatten_test.StringVector_append(self, x)

    def empty(self):
        return _flatten_test.StringVector_empty(self)

    def size(self):
        return _flatten_test.StringVector_size(self)

    def swap(self, v):
        return _flatten_test.StringVector_swap(self, v)

    def begin(self):
        return _flatten_test.StringVector_begin(self)

    def end(self):
        return _flatten_test.StringVector_end(self)

    def rbegin(self):
        return _flatten_test.StringVector_rbegin(self)

    def rend(self):
        return _flatten_test.StringVector_rend(self)

    def clear(self):
        return _flatten_test.StringVector_clear(self)

    def get_allocator(self):
        return _flatten_test.StringVector_get_allocator(self)

    def pop_back(self):
        return _flatten_test.StringVector_pop_back(self)

    def erase(self, *args):
        return _flatten_test.StringVector_erase(self, *args)

    def __init__(self, *args):
        this = _flatten_test.new_StringVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _flatten_test.StringVector_push_back(self, x)

    def front(self):
        return _flatten_test.StringVector_front(self)

    def back(self):
        return _flatten_test.StringVector_back(self)

    def assign(self, n, x):
        return _flatten_test.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _flatten_test.StringVector_resize(self, *args)

    def insert(self, *args):
        return _flatten_test.StringVector_insert(self, *args)

    def reserve(self, n):
        return _flatten_test.StringVector_reserve(self, n)

    def capacity(self):
        return _flatten_test.StringVector_capacity(self)
    __swig_destroy__ = _flatten_test.delete_StringVector
    __del__ = lambda self: None
StringVector_swigregister = _flatten_test.StringVector_swigregister
StringVector_swigregister(StringVector)

class StringVectorVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVectorVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVectorVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _flatten_test.StringVectorVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _flatten_test.StringVectorVector___nonzero__(self)

    def __bool__(self):
        return _flatten_test.StringVectorVector___bool__(self)

    def __len__(self):
        return _flatten_test.StringVectorVector___len__(self)

    def __getslice__(self, i, j):
        return _flatten_test.StringVectorVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _flatten_test.StringVectorVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _flatten_test.StringVectorVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _flatten_test.StringVectorVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _flatten_test.StringVectorVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _flatten_test.StringVectorVector___setitem__(self, *args)

    def pop(self):
        return _flatten_test.StringVectorVector_pop(self)

    def append(self, x):
        return _flatten_test.StringVectorVector_append(self, x)

    def empty(self):
        return _flatten_test.StringVectorVector_empty(self)

    def size(self):
        return _flatten_test.StringVectorVector_size(self)

    def swap(self, v):
        return _flatten_test.StringVectorVector_swap(self, v)

    def begin(self):
        return _flatten_test.StringVectorVector_begin(self)

    def end(self):
        return _flatten_test.StringVectorVector_end(self)

    def rbegin(self):
        return _flatten_test.StringVectorVector_rbegin(self)

    def rend(self):
        return _flatten_test.StringVectorVector_rend(self)

    def clear(self):
        return _flatten_test.StringVectorVector_clear(self)

    def get_allocator(self):
        return _flatten_test.StringVectorVector_get_allocator(self)

    def pop_back(self):
        return _flatten_test.StringVectorVector_pop_back(self)

    def erase(self, *args):
        return _flatten_test.StringVectorVector_erase(self, *args)

    def __init__(self, *args):
        this = _flatten_test.new_StringVectorVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _flatten_test.StringVectorVector_push_back(self, x)

    def front(self):
        return _flatten_test.StringVectorVector_front(self)

    def back(self):
        return _flatten_test.StringVectorVector_back(self)

    def assign(self, n, x):
        return _flatten_test.StringVectorVector_assign(self, n, x)

    def resize(self, *args):
        return _flatten_test.StringVectorVector_resize(self, *args)

    def insert(self, *args):
        return _flatten_test.StringVectorVector_insert(self, *args)

    def reserve(self, n):
        return _flatten_test.StringVectorVector_reserve(self, n)

    def capacity(self):
        return _flatten_test.StringVectorVector_capacity(self)
    __swig_destroy__ = _flatten_test.delete_StringVectorVector
    __del__ = lambda self: None
StringVectorVector_swigregister = _flatten_test.StringVectorVector_swigregister
StringVectorVector_swigregister(StringVectorVector)


def flatten(input_lists):
    return _flatten_test.flatten(input_lists)
flatten = _flatten_test.flatten
# This file is compatible with both classic and new-style classes.


